apiVersion: apps/v1
kind: Deployment
metadata:
  name: nibiru-node
  namespace: nibiru
spec:
  selector:
    matchLabels:
      app: nibiru-node 
  replicas: 1 
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        app: nibiru-node 
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: init-node-key
          image: ghcr.io/nibiruchain/nibiru:latest
          env:
            - name: KEYPASSWD
              valueFrom:
                secretKeyRef:
                  name: validator-key
                  key: password
          securityContext:
            runAsUser: 0
          command: ["/bin/sh","-c"]
          args:
            - >
              set -x;
              apk add sed
              alias nibid=/usr/local/bin/nibid;
              nibid init G_XBT --chain-id=nibiru-itn-1 --home /data;
              (echo $KEYPASSWD; echo $KEYPASSWD) | nibid keys add g-key &> /data/key.txt;
              nibid tendermint unsafe-reset-all --home /data --keep-addr-book;
          volumeMounts:
            - name: chain-data
              mountPath: /data
        - name: init-node-curl
          image: alpine:latest
          securityContext:
            runAsUser: 0
          command: ["/bin/sh","-c"]
          args:
            - >
              set -x;
              apk add curl;
              apk add wget;
              apk add lz4;
              apk add jq;
              curl -s https://networks.itn.nibiru.fi/nibiru-itn-1/genesis > /data/config/genesis.json;
              SNAP_RPC="https://nibiru-testnet.nodejumper.io:443";

              LATEST_HEIGHT=$(curl -s $SNAP_RPC/block | jq -r .result.block.header.height);
              BLOCK_HEIGHT=$((LATEST_HEIGHT - 2000));
              TRUST_HASH=$(curl -s "$SNAP_RPC/block?height=$BLOCK_HEIGHT" | jq -r .result.block_id.hash);

              echo $LATEST_HEIGHT $BLOCK_HEIGHT $TRUST_HASH;

              PEERS="a1b96d1437fb82d3d77823ecbd565c6268f06e34@nibiru-testnet.nodejumper.io:27656";
              sed -i 's|^persistent_peers *=.*|persistent_peers = "'$PEERS'"|' /data/config/config.toml;

              sed -i 's|^enable *=.*|enable = true|' /data/config/config.toml;
              sed -i 's|^rpc_servers *=.*|rpc_servers = "'$SNAP_RPC,$SNAP_RPC'"|' /data/config/config.toml;
              sed -i 's|^trust_height *=.*|trust_height = '$BLOCK_HEIGHT'|' /data/config/config.toml;
              sed -i 's|^trust_hash *=.*|trust_hash = "'$TRUST_HASH'"|' /data/config/config.toml;
              sed -i -e "s~seeds =.*~seeds = \"$SEEDS\"~g" /data/config/config.toml;
              sed -i -e "s~persistent_peers =.*~persistent_peers = \"$PEERS\"~g" /data/config/config.toml;
              sed  -i -e 's~minimum-gas-prices =.*~minimum-gas-prices = "0.025unibi"~g'  /data/config/app.toml;
              sed -i -e "s~^pruning *=.*~pruning = \"custom\"~g" /data/config/app.toml; 
              sed -i -e "s~^pruning-keep-recent *=.*~pruning-keep-recent =\"100\"~g" /data/config/app.toml;
              sed -i -e "s~^pruning-keep-every *=.*~pruning-keep-every = \"0\"~g" /data/config/app.toml;
              sed -i -e "s~^pruning-interval *=.*~pruning-interval = \"10\"~g" /data/config/app.toml;
              wget -O https://snapshots2-testnet.nodejumper.io/nibiru-testnet/wasm.lz4 --inet4-only;
              lz4 -dc wasm.lz4  | tar -xf - -C /data/data;              
          volumeMounts:
            - name: chain-data
              mountPath: /data
      containers:
      - name: nibiru-node 
        image: ghcr.io/nibiruchain/nibiru:latest
        securityContext:
            runAsUser: 0
        command: ["/usr/local/bin/nibid","start"]
        args:
          - --home=/data
          - --rpc.unsafe 
          - --rpc.laddr=tcp://0.0.0.0:26657
          - --rpc.grpc_laddr=tcp://0.0.0.0:26658
        ports:
        - containerPort: 26657
          name: rpc-port
        - containerPort: 26658
          name: grpc-port
        resources:
          limits:
                memory: 6G
                cpu: 4
          requests:
                memory: 6G
                cpu: 2
        readinessProbe:
          tcpSocket:
            port: 26657
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 26657
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: chain-data
          mountPath: /data 
      volumes:
        - name: chain-data
          persistentVolumeClaim:
            claimName: nibiru-node-pvc

