
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - svc.yaml
  - namespace.yaml
  - deployment.yaml
  - ingress.yaml
  - pvc.yaml
  - pool.yaml
  - storageclass.yaml

secretGenerator:
- name: validator-key 
  namespace: nibiru
  type: Opaque
  literals:
  - password=1f2d1e2e67df
  options:
      disableNameSuffixHash: true


