apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nibiru-node-pvc
  labels:
    app: nibiru-node 
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 110Gi
