apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nibiru-node-pvc
  namespace: nibiru
  labels:
    app: nibiru-node 
spec:
  storageClassName: nibiru-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
