apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nibiru-node
spec:
  selector:
    matchLabels:
      app: nibiru-node 
  serviceName: "nibiru-node"
  replicas: 1 
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        app: nibiru-node 
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: init-node
          image: ghcr.io/nibiruchain/nibiru:latest
          command: ["/bin/sh","-c"]
          args:
            - > 
             export HOME=/data;
             export NETWORK=nibiru-itn-1;
             alias nibid=/usr/local/bin/nibid;
             nibid init G_XBT --chain-id=nibiru-itn-1 --home $HOME/.nibid;
             nibid keys add g-key;
             curl -s https://networks.itn.nibiru.fi/$NETWORK/genesis > $HOME/.nibid/config/genesis.json;
             sed -i 's|seeds =.*|seeds = "'$(curl -s https://networks.itn.nibiru.fi/$NETWORK/seeds)'"|g' $HOME/.nibid/config/config.toml;
             sed -i 's/minimum-gas-prices =.*/minimum-gas-prices = "0.025unibi"/g' $HOME/.nibid/config/app.toml;
             sed -i 's|enable =.*|enable = true|g' $HOME/.nibid/config/config.toml
             sed -i 's|rpc_servers =.*|rpc_servers = "'$(curl -s https://networks.itn.nibiru.fi/$NETWORK/rpc_servers)'"|g' $HOME/.nibid/config/config.toml
             sed -i 's|trust_height =.*|trust_height = "'$(curl -s https://networks.itn.nibiru.fi/$NETWORK/trust_height)'"|g' $HOME/.nibid/config/config.toml
             sed -i 's|trust_hash =.*|trust_hash = "'$(curl -s https://networks.itn.nibiru.fi/$NETWORK/trust_hash)'"|g' $HOME/.nibid/config/config.toml
          volumeMounts:
            - name: chain-data
              mountPath: /data
            
      containers:
      - name: nibiru-node 
        image: ghcr.io/nibiruchain/nibiru:latest
        command: ["/usr/local/bin/nibid","start"]
        args:
          - --home /data/.nibid
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: chain-data
          mountPath: /data 
      volumes:
        - name: chain-data
          persistentVolumeClaim:
            claimName: nibiru-node-pvc
