apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nibiru-node
  namespace: nibiru
spec:
  selector:
    matchLabels:
      app: nibiru-node 
  serviceName: "nibiru-node"
  replicas: 1 
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        app: nibiru-node 
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: init-node-key
          image: ghcr.io/nibiruchain/nibiru:latest
          env:
            - name: KEYPASSWD
              valueFrom:
                secretKeyRef:
                  name: validator-key
                  key: password
          securityContext:
            runAsUser: 0
          command: ["/bin/sh","-c"]
          args:
            - > 
              export HOME=/data;
              export NETWORK=nibiru-itn-1;
              alias nibid=/usr/local/bin/nibid;
              nibid init G_XBT --chain-id=nibiru-itn-1 --home $HOME/.nibid;
              (echo $KEYPASSWD; echo $KEYPASSWD) | nibid keys add g-key &> /data/key.txt;
          volumeMounts:
            - name: chain-data
              mountPath: /data
        - name: init-node-curl
          image: curlimages/curl:7.88.1
          securityContext:
            runAsUser: 0
          command: ["/bin/sh","-c"]
          args:
            - > 
              export HOME=/data;
              export NETWORK=nibiru-itn-1;
              apk update;
              apk add --no-cache sed;
              curl -s https://networks.itn.nibiru.fi/$NETWORK/genesis > $HOME/.nibid/config/genesis.json;
              sed -i 's|seeds =.*|seeds = "'$(curl -s https://networks.itn.nibiru.fi/$NETWORK/seeds)'"|g' $HOME/.nibid/config/config.toml;
              sed -i 's/minimum-gas-prices =.*/minimum-gas-prices = "0.025unibi"/g' $HOME/.nibid/config/app.toml;
              sed -i 's|enable =.*|enable = true|g' $HOME/.nibid/config/config.toml
              sed -i 's|rpc_servers =.*|rpc_servers = "'$(curl -s https://networks.itn.nibiru.fi/$NETWORK/rpc_servers)'"|g' $HOME/.nibid/config/config.toml
              sed -i 's|trust_height =.*|trust_height = "'$(curl -s https://networks.itn.nibiru.fi/$NETWORK/trust_height)'"|g' $HOME/.nibid/config/config.toml
              sed -i 's|trust_hash =.*|trust_hash = "'$(curl -s https://networks.itn.nibiru.fi/$NETWORK/trust_hash)'"|g' $HOME/.nibid/config/config.toml
          volumeMounts:
            - name: chain-data
              mountPath: /data
      containers:
      - name: nibiru-node 
        image: ghcr.io/nibiruchain/nibiru:latest
        securityContext:
            runAsUser: 0
        command: ["/usr/local/bin/nibid","start"]
        args:
          - --home=/data/.nibid
          - --rpc.unsafe 
          - --rpc.laddr="tcp://0.0.0.0:26657"
          - --rpc.grpc_laddr="tcp://0.0.0.0:26658"
        ports:
        - containerPort: 26657
          name: rpc-port
        - containerPort: 26658
          name: grpc-port
        resources:
          limits:
                memory: 6G
                cpu: 4
          requests:
                memory: 1G
                cpu: 0.5
        readinessProbe:
          tcpSocket:
            port: 26657
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 26657
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: chain-data
          mountPath: /data 
      volumes:
        - name: chain-data
          persistentVolumeClaim:
            claimName: nibiru-node-pvc
